simulation : main.c input_data.c decide_group.c count_total.c calculate_authority.c output_data.c
						gcc main.c input_data.c decide_group.c count_total.c calculate_authority.c output_data.c -o simulation -lm
